FROM nginx:1.27.4

#指定作者
MAINTAINER liuguofeng

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 80

# 配置文件
ADD 80.conf /etc/nginx/conf.d/80.conf
ADD dist /usr/share/nginx/html/dist
