#指定基础（base）镜像，
FROM mysql:8.0.0

#指定作者
MAINTAINER liuguofeng

ENV TZ=Asia/Shanghai

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 复制SQL初始化脚本到容器中
COPY init.sql /docker-entrypoint-initdb.d